import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stewpot Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.topBar}>

          <div className={styles.topBarLeft}>

            <div className={styles.topBtn}>
              <Image
              src="/Donate.svg"
              width={50}
              height={50}  
              alt="Image Not Supported"
              /> 
              <h3 style={{'font-size': '1.5rem'}}>DONATE</h3>
            </div>

          </div>

          <div className={styles.topBarRight}> 

            <div className={styles.topBtn}>
              <h3 style={{'font-size': '1rem'}}>I NEED HELP</h3>
              <Image
              src="/I_need_help.svg"
              width={50}
              height={50}  
              alt="Image Not Supported"
              /> 
            </div>

            <div className={styles.topBtn} style={{'margin-left': '2rem'}}>
              <h3 style={{'font-size': '1rem'}}>I WANT TO HELP</h3>
              <Image
              src="/I_want_to_help.svg"
              width={50}
              height={50}  
              alt="Image Not Supported"
              />
              
             <div className={styles.background1}></div>
             <Image
             src="frontend\public\iStock-1297602786.jpg"
             width={75%}
             height={75%}
             alt="image Not Supported"
             />
            </div>

          </div>

        </div>  

      </main>


    </div>
  )
  
}
